function injectResearchRoomStyle(){
  if(document.getElementById('researchRoomStyle'))return;
  const s=document.createElement('style');s.id='researchRoomStyle';s.textContent=`
    .research-room-card{border:1px solid #1b2530;background:#080d13;border-radius:12px;padding:12px;margin:0 0 12px;box-shadow:0 0 22px rgba(83,65,210,.18)}
    .research-head{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:10px}.research-head b{color:#f2f6fb;font-size:13px}.research-head span{color:#8b98a8;font-size:11px}.research-head button,.research-form button{background:#122033;border:1px solid #36506b;color:#d7ecff;border-radius:999px;padding:7px 11px;font-size:11px;font-weight:900;cursor:pointer}
    .research-grid{display:grid;grid-template-columns:1fr 1.2fr;gap:10px}.research-panel{border:1px solid #1b2530;background:#070b10;border-radius:10px;padding:10px;min-height:150px}.research-panel h4{margin:0 0 8px;color:#d7ecff;font-size:12px}.research-performance{display:grid;grid-template-columns:1.4fr .45fr .45fr .55fr .7fr;gap:0;border:1px solid #1b2530;border-radius:8px;overflow:hidden}.research-performance div{padding:7px;border-bottom:1px solid #1b2530;color:#c9d1d9;font-size:11px}.research-performance .h{background:#10161d;color:#d7ecff;font-weight:900;text-transform:uppercase;font-size:9.5px}.research-performance div:nth-last-child(-n+5){border-bottom:0}.research-chat{white-space:pre-line;color:#c9d1d9;font-size:12px;line-height:1.55;max-height:240px;overflow:auto}.research-form{display:grid;grid-template-columns:1fr 72px;gap:8px;margin-top:10px}.research-form input{background:#070b10;border:1px solid #263442;color:#f2f6fb;border-radius:999px;padding:9px 12px;font-size:12px}.research-usage{color:#8b98a8;font-size:10.5px;margin-top:6px}.research-good{color:#7ff0ad!important}.research-bad{color:#ff8a94!important}.research-wait{color:#f0b35a!important}
  `;document.head.appendChild(s);
}
async function researchApi(action,payload={}){const r=await fetch('/api/research',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});return r.json();}
function ensureResearchRoom(){
  injectResearchRoomStyle();
  const view=document.getElementById('paperView');const runner=document.getElementById('runnerStatusCard');const strategy=document.getElementById('strategyLab');
  if(!view||document.getElementById('researchRoomCard'))return;
  const card=document.createElement('div');card.id='researchRoomCard';card.className='research-room-card';
  card.innerHTML=`<div class="research-head"><div><b>AI RESEARCH ROOM</b> <span>GPT research partner · 基于云端 paper 数据</span></div><button id="researchRefreshBtn">Load Data</button></div><div class="research-grid"><div class="research-panel"><h4>Strategy Performance</h4><div class="research-performance" id="researchPerf"></div></div><div class="research-panel"><h4>Research Chat</h4><div class="research-chat" id="researchChat">问我：哪个 strategy 表现最好？哪个规则要改？样本够不够？</div><div class="research-form"><input id="researchInput" placeholder="用中文问 AI 研究系统..."/><button id="researchAskBtn">Ask</button></div><div class="research-usage" id="researchUsage"></div></div></div>`;
  if(runner)runner.insertAdjacentElement('afterend',card);else if(strategy)strategy.insertAdjacentElement('beforebegin',card);else view.prepend(card);
  document.getElementById('researchRefreshBtn')?.addEventListener('click',loadResearchSummary);
  document.getElementById('researchAskBtn')?.addEventListener('click',askResearchRoom);
  document.getElementById('researchInput')?.addEventListener('keydown',e=>{if(e.key==='Enter')askResearchRoom()});
}
function renderResearchPerformance(data){ensureResearchRoom();const box=document.getElementById('researchPerf');if(!box)return;const perf=data?.strategyPerformance||[];box.innerHTML='<div class="h">Strategy</div><div class="h">Trades</div><div class="h">Win%</div><div class="h">Avg R</div><div class="h">Best</div>';if(!perf.length){box.insertAdjacentHTML('beforeend','<div>等待 closed paper trades</div><div>-</div><div>-</div><div>-</div><div>-</div>');return;}perf.slice(0,5).forEach(p=>{const cls=Number(p.avgR)>0?'research-good':Number(p.avgR)<0?'research-bad':'research-wait';box.insertAdjacentHTML('beforeend',`<div>${p.name}</div><div>${p.total}</div><div>${p.winRate}%</div><div class="${cls}">${Number(p.avgR).toFixed(2)}R</div><div>${p.bestSymbol||'-'}</div>`)});}
async function loadResearchSummary(){ensureResearchRoom();const chat=document.getElementById('researchChat');if(chat)chat.textContent='读取 Supabase research data...';const res=await researchApi('summary');if(res.ok){renderResearchPerformance(res.data);if(chat)chat.textContent='Research data loaded. 你可以开始问：这个 strategy 要不要改？哪个 symbol 更适合？样本够不够？';}else{if(chat)chat.textContent='Research data load failed: '+(res.error||'unknown');}}
async function askResearchRoom(){ensureResearchRoom();const input=document.getElementById('researchInput');const chat=document.getElementById('researchChat');const usage=document.getElementById('researchUsage');const q=input?.value.trim();if(!q)return;if(chat)chat.textContent='Jack：'+q+'\n\nAI 正在读取云端数据研究...';if(input)input.value='';const res=await researchApi('ask',{question:q});if(res.ok){renderResearchPerformance(res.data);if(chat)chat.textContent='Jack：'+q+'\n\nAI：\n'+String(res.answer||'');if(usage&&res.usage)usage.textContent='Tokens: '+res.usage.totalTokens+' · Cost: $'+Number(res.usage.estimatedCost||0).toFixed(4);try{if(typeof addMonthlyCost==='function')addMonthlyCost(res.usage?.estimatedCost||0)}catch{}}else{if(chat)chat.textContent='Research failed: '+(res.error||'unknown');}}
(function(){setTimeout(()=>{ensureResearchRoom();loadResearchSummary()},4500);window.loadResearchSummary=loadResearchSummary;window.askResearchRoom=askResearchRoom;})();
