const WATCHLIST = ['GBPJPY','USDJPY','XAUUSD','GBPUSD','EURUSD','AUDJPY','USDCHF','EURGBP'];
const STRATEGIES = [
  { id:'S1_BREAKOUT_RSPACE', name:'Breakout + R Space', market:'trend / breakout' },
  { id:'S2_SUPPORT_REJECTION', name:'Support Rejection', market:'range / pullback' },
  { id:'S3_RESIST_REJECTION', name:'Resistance Rejection', market:'range / rejection' },
  { id:'S4_TREND_CONTINUATION', name:'Trend Continuation', market:'strong trend' },
  { id:'S5_NO_MIDDLE_PRICE', name:'Middle Price Filter', market:'filter' }
];

function json(res, status, payload){res.status(status).setHeader('Content-Type','application/json');res.end(JSON.stringify(payload));}
function cfg(){return {url:process.env.SUPABASE_URL,key:process.env.SUPABASE_SERVICE_ROLE_KEY,cronSecret:process.env.CRON_SECRET||''};}
async function sb(path, options={}){const {url,key}=cfg();if(!url||!key)throw new Error('Missing Supabase env');const r=await fetch(`${url}/rest/v1/${path}`,{...options,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',...(options.headers||{})}});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok)throw new Error(typeof data==='string'?data:(data?.message||'Supabase error'));return data;}
function fmt(n){const x=Number(n);if(!Number.isFinite(x))return null;return Math.abs(x)>=10?Number(x.toFixed(2)):Number(x.toFixed(4));}
function risk(symbol){if(String(symbol).includes('JPY'))return 0.40;if(symbol==='XAUUSD')return 12;return 0.0040;}
function pipSize(symbol){const s=String(symbol||'').toUpperCase();if(s.includes('JPY'))return 0.01;if(s==='XAUUSD')return 1;if(s==='DXY'||s==='US10Y')return 0.01;return 0.0001;}
function pips(symbol,a,b){const x=Number(a),y=Number(b);if(!Number.isFinite(x)||!Number.isFinite(y))return null;return Math.abs(x-y)/pipSize(symbol);}
function tradeRow(t){return {id:String(t.id),symbol:t.symbol||null,strategy_id:t.strategyId||null,strategy_name:t.strategyName||null,status:t.status||null,outcome:t.outcome||null,direction:t.direction||null,potential_r:Number.isFinite(Number(t.potentialR))?Number(t.potentialR):null,gpt_tokens:Number.isFinite(Number(t.gptTokens))?Number(t.gptTokens):null,gpt_cost:Number.isFinite(Number(t.gptCost))?Number(t.gptCost):null,payload:t,updated_at:new Date().toISOString()};}
async function getCloudTrades(){const rows=await sb('paper_trades?select=payload&order=created_at.desc&limit=500',{method:'GET'});return (rows||[]).map(r=>r.payload).filter(Boolean);}
async function saveTrades(trades){if(!trades.length)return [];return sb('paper_trades?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify(trades.map(tradeRow))});}
async function saveRun(run){return sb('strategy_runs?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify([{id:String(run.id),opened:run.opened||0,rejected:run.rejected||0,payload:run}])});}
async function saveSnowball(item){return sb('snowball_memory?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify([{id:String(item.id||Date.now()+Math.random()),type:item.type||null,symbol:item.symbol||null,payload:item}])});}
function hasDuplicate(trades,symbol,strategyId,direction){return trades.some(t=>t.status==='PAPER OPEN'&&t.symbol===symbol&&t.strategyId===strategyId&&t.direction===direction);}
function chooseCandidate(symbol,data){const levels=data.levels||{},h1=levels.H1||{},h4=levels.H4||{},w1=levels.W1||{},m1=levels.M1||{};const entry=Number(data.price),r=risk(symbol);if(!Number.isFinite(entry))return {verdict:'NO PAPER',reason:'no price'};
  const build=(strategy,direction,target,reason,base='PAPER WATCH')=>{const dir=direction==='LONG'?1:-1;let spaceLevel=Number(target);if(!Number.isFinite(spaceLevel))spaceLevel=entry+dir*r*3;const space=Math.abs(spaceLevel-entry),potentialR=space/r;let warning='';['W1','M1'].forEach(tf=>{const l=levels[tf]||{};const t=direction==='LONG'?Number(l.nextResistance||l.resistance):Number(l.nearestSupport||l.support);if(Number.isFinite(t)){const rr=Math.abs(t-entry)/r;if(rr<3)warning+=(warning?' · ':'')+`${tf} major ${rr.toFixed(1)}R`;}if(direction==='LONG'&&l.status==='NEAR RESISTANCE')warning+=(warning?' · ':'')+`${tf} near resistance`;if(direction==='SHORT'&&l.status==='NEAR SUPPORT')warning+=(warning?' · ':'')+`${tf} near support`;});let verdict=base;if(potentialR<2)verdict='NO PAPER';else if(potentialR<3||warning)verdict='PAPER ONLY';const stop=entry-dir*r,tp3=entry+dir*Math.min(r*3,Math.max(r,space*0.9)),tp5=entry+dir*Math.min(r*5,Math.max(r,space*0.95));return {symbol,direction,strategyId:strategy.id,strategyName:strategy.name,entry:fmt(entry),stop:fmt(stop),tp3:fmt(tp3),tp5:fmt(tp5),spaceLevel:fmt(spaceLevel),spacePips:pips(symbol,entry,spaceLevel),potentialR,verdict,higherTfWarning:warning,reason:`${strategy.name}: ${reason}. Space ${potentialR.toFixed(1)}R${warning?' · HTF '+warning:''}.`,marketType:strategy.market,exitStrategyId:'E1_TP3_STOP_72H'};};
  const nextR=Number(h4.nextResistance||h1.nextResistance||h4.resistance||h1.resistance);const nearS=Number(h4.nearestSupport||h1.nearestSupport||h4.support||h1.support);
  const candidates=[];if(h1.status==='BREAKOUT'||h4.status==='BREAKOUT')candidates.push(build(STRATEGIES[0],'LONG',nextR,'cloud breakout research'));if(h1.status==='NEAR SUPPORT'||h4.status==='NEAR SUPPORT')candidates.push(build(STRATEGIES[1],'LONG',nextR,'cloud support reaction research','PAPER ONLY'));if(h1.status==='NEAR RESISTANCE'||h4.status==='NEAR RESISTANCE')candidates.push(build(STRATEGIES[2],'SHORT',nearS,'cloud resistance rejection research','PAPER ONLY'));if(h1.status==='BREAKOUT'&&h4.status==='BREAKOUT')candidates.push(build(STRATEGIES[3],'LONG',nextR,'cloud trend continuation research'));if(!candidates.length)return {symbol,strategyId:'S5_NO_MIDDLE_PRICE',strategyName:'Middle Price Filter',verdict:'NO PAPER',reason:'middle/range; no clean Abu edge'};return candidates.sort((a,b)=>Number(b.potentialR||0)-Number(a.potentialR||0))[0];}
async function fetchLevels(req,symbol){const proto=req.headers['x-forwarded-proto']||'https';const host=req.headers.host||process.env.VERCEL_URL;const base=host?`${proto}://${host}`:'';const r=await fetch(`${base}/api/levels?symbol=${encodeURIComponent(symbol)}`);return r.json();}
function closeTradeIfHit(t,price){const long=t.direction==='LONG',short=t.direction==='SHORT';if(long&&price>=Number(t.tp3))return 'WIN';if(long&&price<=Number(t.stop))return 'LOSS';if(short&&price<=Number(t.tp3))return 'WIN';if(short&&price>=Number(t.stop))return 'LOSS';if(Date.now()-Number(t.id)>72*60*60*1000)return 'EXPIRED';return null;}
async function runCron(req){let trades=await getCloudTrades();let opened=0,rejected=0,closed=0;const changed=[];for(const t of trades.filter(x=>x.status==='PAPER OPEN')){try{const data=await fetchLevels(req,t.symbol);const price=Number(data.price);if(!Number.isFinite(price))continue;t.lastCheckedAt=new Date().toLocaleString();t.lastPrice=price;const outcome=closeTradeIfHit(t,price);if(outcome){t.status='PAPER CLOSED';t.outcome=outcome;t.reviewedAt=new Date().toLocaleString();t.closePrice=price;t.needsGptReview=true;t.review=`Cloud rule review: ${outcome} at ${fmt(price)}. GPT review can be generated from Paper page.`;closed++;changed.push(t);await saveSnowball({type:'CLOUD_PAPER_CLOSED',time:t.reviewedAt,symbol:t.symbol,outcome,trade:t});}}catch(e){}}
  for(const symbol of WATCHLIST){try{const data=await fetchLevels(req,symbol);const c=chooseCandidate(symbol,data);if(!c||c.verdict==='NO PAPER'){rejected++;continue;}if(hasDuplicate(trades,symbol,c.strategyId,c.direction)){rejected++;continue;}const t={id:String(Date.now()+Math.floor(Math.random()*99999)),time:new Date().toLocaleString(),status:'PAPER OPEN',outcome:'TRACKING',review:'',source:data.source,levels:data.levels,researchVersion:'v5-cloud-cron',autoGenerated:true,cloudGenerated:true,learningMode:true,score:'-',setup:c.strategyName,...c};trades.unshift(t);changed.push(t);opened++;await saveSnowball({type:'CLOUD_AI_STRATEGY_OPEN',time:t.time,symbol:t.symbol,strategyId:t.strategyId,strategyName:t.strategyName,potentialR:t.potentialR,trade:t});}catch(e){rejected++;}}
  await saveTrades(changed);const run={id:String(Date.now()),time:new Date().toLocaleString(),source:'vercel_cron',opened,rejected,closed,changed:changed.map(t=>({id:t.id,symbol:t.symbol,status:t.status,outcome:t.outcome,strategyId:t.strategyId}))};await saveRun(run);return run;}
module.exports=async function handler(req,res){try{const {cronSecret}=cfg();const provided=req.headers['x-cron-secret']||req.query.secret||'';if(cronSecret&&provided!==cronSecret)return json(res,401,{ok:false,error:'unauthorized'});const run=await runCron(req);return json(res,200,{ok:true,run});}catch(error){return json(res,200,{ok:false,error:error.message||'cron error'});}};
